{"title":"Memasang Dropbox di Ubuntu 14.04 x64 headless: kesalahan izin","draft":false,"url":"/memasang-dropbox-di-ubuntu-1404-x64-headless-kesalahan-izin-a6w7vpts","votes":"4","answers_count":"5","categories":["Komputer"],"tags":["linux","ubuntu","permissions","dropbox"],"snippet":"Jadi saya mencoba memasang Dropbox (sebagai root) mengikuti petunjuk yang tampaknya mudah di dropbox.com:  cd ~ &amp;&amp; wget -O - \"https://www.dropbox.com/download?plat=lnx.x86_64\" | tar xzf -~/.dropbox-dist/dropboxd  Perintah pertama dijalankan tanpa masalah, namun...","body":"<p> Jadi saya mencoba memasang Dropbox (sebagai root) mengikuti petunjuk yang tampaknya mudah di dropbox.com: </p> <pre><code>cd ~ &amp;&amp; wget -O - \"https://www.dropbox.com/download?plat=lnx.x86_64\" | tar xzf -\n~/.dropbox-dist/dropboxd\n</code></pre> <p> Perintah pertama dijalankan tanpa masalah, namun perintah kedua memicu pesan kesalahan ini: </p>\n\n<blockquote>\n  <p> Tidak dapat memulai Dropbox.\n  Ini biasanya karena kesalahan izin. Menyimpan folder rumah Anda di jaringan berbagi juga dapat menyebabkan kesalahan. </p>\n  \n  <p> Dapatkan bantuan lebih lanjut di <a href=\"https://www.dropbox.com/c/help/permissions_error\" rel=\"nofollow noopener\" target=\"_blank\"> https://www.dropbox.com/c/help/permissions_error </a></p>\n  \n  <p> Silakan hubungi dukungan Dropbox dengan info berikut untuk bantuan: </p>\n  \n  <p> /tmp/dropbox_errorgel_th.txt </p>\n</blockquote>\n\n<p> Isi file itu: </p> <pre><code>bn.BUILD_KEY: Dropbox\n bn.VERSION: 2.10.28\n bn.DROPBOXEXT_VERSION: failed\n bn.is_frozen: True\n pid: 755\n ppid: 460\n ppid exe: '/bin/bash'\n uid: 0\n user_info: pwd.struct_passwd(pw_name='root', pw_passwd='x', pw_uid=0, pw_gid=0,           pw_gecos='root', pw_dir='/root', pw_shell='/bin/bash')\n effective_user_info: pwd.struct_passwd(pw_name='root', pw_passwd='x', pw_uid=0, pw_gid=0, pw_gecos='root', pw_dir='/root', pw_shell='/bin/bash')\n euid: 0\n gid: 0\n egid: 0\n group_info: grp.struct_group(gr_name='root', gr_passwd='x', gr_gid=0, gr_mem=[])\n effective_group_info: grp.struct_group(gr_name='root', gr_passwd='x', gr_gid=0, gr_mem=[])\n LD_LIBRARY_PATH: None\n cwd: '/root'\n     real_path='/root'\n            mode=040700 uid=0   gid=0\n     parent mode=040755 uid=0   gid=0\n HOME: u'/root'\n appdata: u'/root/.dropbox/instance1'\n         real_path=u'/root/.dropbox/instance1'\n                mode=040700 uid=0   gid=0\n         parent mode=040700 uid=0   gid=0\n dropbox_path: u'/root/Dropbox'\n              real_path=u'/root/Dropbox'\n                        not found\n              parent    mode=040700 uid=0   gid=0\n sys_executable: '/root/.dropbox-dist/dropbox-lnx.x86_64-2.10.28/dropbox'\n                real_path='/root/.dropbox-dist/dropbox-lnx.x86_64-2.10.28/dropbox'\n                        mode=0100755    uid=1000    gid=1002\n                parent  mode=040755 uid=1000    gid=1002\n trace.__file__: '/root/.dropbox-dist/dropbox-lnx.x86_64-     2.10.28/library.zip/dropbox/boot_error.pyc'\n                real_path='/root/.dropbox-dist/dropbox-lnx.x86_64-2.10.28/library.zip/dropbox/boot_error.pyc'\n                        not found\n                parent  not found\n tempdir: '/tmp'\n         real_path='/tmp'\n                mode=041777 uid=0   gid=0\n         parent mode=040755 uid=0   gid=0\n Traceback (most recent call last):\n  File \"dropbox/client/main.py\", line 2369, in main_startup\n  File \"dropbox/client/main.py\", line 1421, in run\n  File \"dropbox/client/main.py\", line 920, in activate_translation\n  File \"dropbox/i18n.py\", line 234, in activate_translation\n  File \"dropbox/i18n.py\", line 279, in system_lang_code\n  File \"dropbox/i18n.py\", line 401, in get_system_languages\n  File \"locale.py\", line 511, in getdefaultlocale\n  File \"locale.py\", line 443, in _parse_localename\n ValueError: unknown locale: UTF-8\n</code></pre> <p> Cukup pemula Linux di sini ... Ada yang punya ide? </p>","source":"https://superuser.com/questions/801675/installing-dropbox-on-headless-ubuntu-14-04-x64-permissions-error","author":"<a href=\"https://superuser.com/users/360637/rits\" target=\"_blank\" rel=\"nofollow noopener\"><span itemprop=\"name\">Rits</span></a>","replies":[{"reply":"Sudahkah Anda mencoba menginstalnya dengan pengguna biasa? Biasanya Anda tidak ingin menggunakan root untuk Dropbox.","author":"<a href=\"https://superuser.com/users/304761/max890\" target=\"_blank\" rel=\"nofollow noopener\">max890</a>"}],"answers":[{"answer":"<p> Saya memiliki masalah yang sama saat menginstal drop box dari jarak jauh pada mesin ubuntu 14.04. Saya bisa mengatasinya dengan menjalankan dropboxd dengan izin root untuk pertama kalinya. </p> <pre><code>sudo ~/.dropbox-dist/dropboxd\n</code></pre> <p> Setelah diatur, tidak lagi membutuhkan hak root dan berjalan dengan benar di bawah akun pengguna saya. Saya baru saja menggunakan alat CLI dropbox untuk melakukannya: </p> <pre><code>~$ dropbox status\nUp to date\n~$ dropbox stop\nDropbox daemon stopped.\n~$ dropbox start\nStarting Dropbox...Dropbox isn't running!\nDone!\n</code></pre> <p> HTH :) </p>","votes":"5","source":"https://superuser.com/a/803153","author":"<a href=\"https://superuser.com/users/219695/tom-m\" target=\"_blank\" rel=\"nofollow noopener\"><span itemprop=\"name\">Tom M.</span></a>","replies":[{"reply":"Saat meninjau jawaban saya, saya baru menyadari bahwa saya juga memiliki masalah dengan pengaturan lokal. Cobalah untuk &quot;mengekspor LC_ALL = C&quot; dan jalankan kembali dropboxd.","author":"<a href=\"https://superuser.com/users/219695/tom-m\" target=\"_blank\" rel=\"nofollow noopener\">Tom M.</a>"},{"reply":"Berjalan dengan izin root tidak berpengaruh, namun ekspor LC_ALL = &quot;en_US.UTF-8&quot; dan ekspor LANGUAGE = &quot;en_US.UTF-8&quot; berhasil. Terima kasih!","author":"<a href=\"https://superuser.com/users/360637/rits\" target=\"_blank\" rel=\"nofollow noopener\">Rits</a>"}]},{"answer":"<p> Anda perlu memulai koneksi ke server tanpa -X: </p>\n\n<p> ssh pengguna @ server </p>\n\n<p> dan tidak </p>\n\n<p> ssh -X pengguna @ server </p>\n\n<p> Lalu lari </p>\n\n<p> sudo ~ / .dropbox-dist / dropboxd </p>\n\n<p> dan Anda akan menerima pesan seperti ini:\nKomputer ini tidak ditautkan ke akun Dropbox mana pun ...\nSilakan kunjungi <a href=\"https://www.dropbox.com/cli_link_nonce?nonce=some_string\" rel=\"nofollow noopener\" target=\"_blank\"> https://www.dropbox.com/cli_link_nonce?nonce=some_string </a> untuk menautkan perangkat ini. </p>\n\n<p> Gunakan tautan ini ke browser apa pun dan kemudian dropbox Anda akan ditautkan </p>","votes":"2","source":"https://superuser.com/a/1224717","author":"<a href=\"https://superuser.com/users/744295/daniel\" target=\"_blank\" rel=\"nofollow noopener\"><span itemprop=\"name\">daniel</span></a>","replies":[{"reply":"Astaga. Saya beralih dari dempul ke MobaXterm dan beralih server. Tidak akan pernah bisa menebak ini, meskipun petunjuknya ada di sana!","author":"<a href=\"https://superuser.com/users/905762/mgriebe\" target=\"_blank\" rel=\"nofollow noopener\">mgriebe</a>"}]},{"answer":"<p> Masalah serupa, menyiapkan dropbox pada instalasi linux headless. Satu-satunya perbedaan adalah saya tidak memiliki root. Ini adalah lingkungan cluster sehingga direktori home default berada di Luster FS. Saya menyalin <code>.dropbox-dist</code> ke jalur di disk lokal dan melakukan ini: </p> <pre><code>export HOME=\"/your/path/to\"; .dropbox-dist/dropboxd\n</code></pre>","votes":"0","source":"https://superuser.com/a/965487","author":"<a href=\"https://superuser.com/users/490726/zastard\" target=\"_blank\" rel=\"nofollow noopener\"><span itemprop=\"name\">zastard</span></a>","replies":[]},{"answer":"<p> Selain jawaban @ Tom, ada kasus tepi lain di mana kesalahan yang sama di atas diberikan. Jika Anda terhubung ke mesin yang dimaksud melalui SSH dengan penerusan X11 diaktifkan, dropbox akan mencoba dan mencari berbagai pustaka terkait X11 yang mungkin tidak diinstal. </p>\n\n<p> Ini diisyaratkan dalam file log yang <code>dropboxd</code> menghasilkan: </p> <pre><code>...\nTraceback (most recent call last):\n  File \"dropbox/client/main.py\", line 5050, in main_startup\n  File \"dropbox/client/main.py\", line 2173, in run\n  File \"ui/common/uikit.py\", line 473, in create_ui_kit\n  File \"dropbox/client/ui/qt/__init__.py\", line 28, in &lt;module&gt;\n  File \"PyQt5/QtWidgets.py\", line 14, in &lt;module&gt;\nImportError: libXdamage.so.1: cannot open shared object file: No such file or directory\n</code></pre> <p> Solusinya cukup dengan menonaktifkan penerusan X11 saat menjalankan klien. </p>","votes":"0","source":"https://superuser.com/a/1105320","author":"<a href=\"https://superuser.com/users/446945/stav\" target=\"_blank\" rel=\"nofollow noopener\"><span itemprop=\"name\">stav</span></a>","replies":[]},{"answer":"<p> Saya memiliki masalah yang sama di OpenSUSE. Saya menyelesaikannya dengan menghapus file tersembunyi (tekan: <kbd> Ctrl + h </kbd> pada folder utama untuk melihatnya) terkait dengan dropbox, yaitu di <code>/home/user/.dropbox*</code>. </p>\n\n<p> Di dalam file tersembunyi tersebut terdapat file yang terkait dengan konfigurasi dropbox. Setelah ini, coba instal kembali dropbox; yang mungkin memecahkan masalah. </p>","votes":"-1","source":"https://superuser.com/a/1067730","author":"<a href=\"https://superuser.com/users/585202/bratti\" target=\"_blank\" rel=\"nofollow noopener\"><span itemprop=\"name\">Bratti</span></a>","replies":[]}]}
